(define-package "snipsearch" "20210219.1616" "Package to enable macros" '((emacs "27.1"))
  :author '(("Dominik Keller" . "user@user.com"))
  :maintainer '(("Dominik Keller" . "user@user.com"))
  :keywords '("Convenience")
  :url "https://www.github.com/domse007/snipsearch")
